### ISSUE TITLE
OutOfMemoryError: Java heap space when fetching urls

### ISSUE THREAD

**Issue by JustDoom** [JustDoom/ArchiveEngineBackend#1]
Once it has been running for a while it eventually gives a Java Heap Error. It happens whenever urls are fetched if the database is big enough it seems. Maybe there are links that are too long for it to handle? Happened earlier but added java ram heap size limits and that fixed it for a while but it's happening again

```
java.lang.OutOfMemoryError: Java heap space
        at java.base/java.util.ArrayList.<init>(ArrayList.java:156) ~[na:na]
        at org.hibernate.collection.spi.PersistentBag.getSnapshot(PersistentBag.java:226) ~[hibernate-core-6.1.7.Final.jar!/:6.1.7.Final]
        at org.hibernate.engine.spi.CollectionEntry.postInitialize(CollectionEntry.java:203) ~[hibernate-core-6.1.7.Final.jar!/:6.1.7.Final]
        at org.hibernate.sql.results.internal.ResultsHelper.finalizeCollectionLoading(ResultsHelper.java:153) ~[hibernate-core-6.1.7.Final.jar!/:6.1.7.Final]
        at org.hibernate.sql.results.internal.LoadingCollectionEntryImpl.finishLoading(LoadingCollectionEntryImpl.java:82) ~[hibernate-core-6.1.7.Final.jar!/:6.1.7.Final]
        at org.hibernate.sql.results.jdbc.internal.JdbcValuesSourceProcessingStateStandardImpl.finishLoadingCollections(JdbcValuesSourceProcessingStateStandardImpl.java:258) ~[hibernate-core-6.1.7.Final.jar!/:6.1.7.Final]
        at org.hibernate.sql.results.jdbc.internal.JdbcValuesSourceProcessingStateStandardImpl.finishUp(JdbcValuesSourceProcessingStateStandardImpl.java:189) ~[hibernate-core-6.1.7.Final.jar!/:6.1.7.Final]
        at org.hibernate.sql.results.spi.ListResultsConsumer.consume(ListResultsConsumer.java:204) ~[hibernate-core-6.1.7.Final.jar!/:6.1.7.Final]
        at org.hibernate.sql.results.spi.ListResultsConsumer.consume(ListResultsConsumer.java:33) ~[hibernate-core-6.1.7.Final.jar!/:6.1.7.Final]
        at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.doExecuteQuery(JdbcSelectExecutorStandardImpl.java:443) ~[hibernate-core-6.1.7.Final.jar!/:6.1.7.Final]
        at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.executeQuery(JdbcSelectExecutorStandardImpl.java:166) ~[hibernate-core-6.1.7.Final.jar!/:6.1.7.Final]
        at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.list(JdbcSelectExecutorStandardImpl.java:91) ~[hibernate-core-6.1.7.Final.jar!/:6.1.7.Final]
        at org.hibernate.sql.exec.spi.JdbcSelectExecutor.list(JdbcSelectExecutor.java:31) ~[hibernate-core-6.1.7.Final.jar!/:6.1.7.Final]
        at org.hibernate.loader.ast.internal.CollectionLoaderSingleKey.load(CollectionLoaderSingleKey.java:121) ~[hibernate-core-6.1.7.Final.jar!/:6.1.7.Final]
        at org.hibernate.persister.collection.AbstractCollectionPersister.initialize(AbstractCollectionPersister.java:789) ~[hibernate-core-6.1.7.Final.jar!/:6.1.7.Final]
        at org.hibernate.event.internal.DefaultInitializeCollectionEventListener.onInitializeCollection(DefaultInitializeCollectionEventListener.java:75) ~[hibernate-core-6.1.7.Final.jar!/:6.1.7.Final]
        at org.hibernate.internal.SessionImpl$$Lambda$1490/0x000000080151ed98.accept(Unknown Source) ~[na:na]
        at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:107) ~[hibernate-core-6.1.7.Final.jar!/:6.1.7.Final]
        at org.hibernate.internal.SessionImpl.initializeCollection(SessionImpl.java:1710) ~[hibernate-core-6.1.7.Final.jar!/:6.1.7.Final]
        at org.hibernate.collection.spi.AbstractPersistentCollection.lambda$initialize$3(AbstractPersistentCollection.java:617) ~[hibernate-core-6.1.7.Final.jar!/:6.1.7.Final]
        at org.hibernate.collection.spi.AbstractPersistentCollection$$Lambda$1489/0x000000080151e710.doWork(Unknown Source) ~[na:na]
        at org.hibernate.collection.spi.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:265) ~[hibernate-core-6.1.7.Final.jar!/:6.1.7.Final]
        at org.hibernate.collection.spi.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:615) ~[hibernate-core-6.1.7.Final.jar!/:6.1.7.Final]
        at org.hibernate.collection.spi.AbstractPersistentCollection.forceInitialization(AbstractPersistentCollection.java:813) ~[hibernate-core-6.1.7.Final.jar!/:6.1.7.Final]
        at org.hibernate.engine.internal.StatefulPersistenceContext$$Lambda$1418/0x00000008014d0ae0.accept(Unknown Source) ~[na:na]
        at org.hibernate.engine.internal.StatefulPersistenceContext.initializeNonLazyCollections(StatefulPersistenceContext.java:1003) ~[hibernate-core-6.1.7.Final.jar!/:6.1.7.Final]
        at org.hibernate.engine.internal.StatefulPersistenceContext.initializeNonLazyCollections(StatefulPersistenceContext.java:989) ~[hibernate-core-6.1.7.Final.jar!/:6.1.7.Final]
        at org.hibernate.sql.results.spi.ListResultsConsumer.consume(ListResultsConsumer.java:225) ~[hibernate-core-6.1.7.Final.jar!/:6.1.7.Final]
        at org.hibernate.sql.results.spi.ListResultsConsumer.consume(ListResultsConsumer.java:33) ~[hibernate-core-6.1.7.Final.jar!/:6.1.7.Final]
        at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.doExecuteQuery(JdbcSelectExecutorStandardImpl.java:443) ~[hibernate-core-6.1.7.Final.jar!/:6.1.7.Final]
        at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.executeQuery(JdbcSelectExecutorStandardImpl.java:166) ~[hibernate-core-6.1.7.Final.jar!/:6.1.7.Final]
        at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.list(JdbcSelectExecutorStandardImpl.java:91) ~[hibernate-core-6.1.7.Final.jar!/:6.1.7.Final]
```

**Comment by JustDoom** [comment]
Fixed it! It was a cascade type issue. It would load every url under a domain into ram
